### PR TITLE
feat: add local resource pack hosting for dev environment

### PR DESCRIPTION
**Pull request by dm432**

### CODE REVIEW

**Review by ChechuDEV — APPROVED** [review]
Seems pretty great to me 👍

**Review by ChechuDEV — APPROVED** [review]
Great, just to keep in mind, it might be great if we add a brief introduction to collaboration in the Readme

**Comment by ChechuDEV** [comment]
A bigger one not just a take a look at contribution ig, or will that disturb the main purpose of readme?

**Comment by dm432** [comment]
> A bigger one not just a take a look at contribution ig, or will that disturb the main purpose of readme?

The cotribution md is linked in the readme

**Pull request merged**
